#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -lt 2 ]; then
  echo "Usage: tooling/create_app_shell.sh <app_name> <brand_profile:consumer|doctor> [env:dev|staging|prod]"
  exit 1
fi

APP_NAME="$1"
BRAND_PROFILE="$2"
APP_ENV="${3:-dev}"
APP_DIR="apps/${APP_NAME}"

if [ -d "$APP_DIR" ]; then
  echo "Error: $APP_DIR already exists"
  exit 1
fi

flutter create --project-name "$APP_NAME" --org com.example "$APP_DIR"

cat > "$APP_DIR/pubspec.yaml" <<PUBSPEC
name: ${APP_NAME}
description: ${APP_NAME} app shell generated by tooling/create_app_shell.sh.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  foundation:
    path: ../../packages/foundation
  design_system:
    path: ../../packages/design_system
  shared:
    path: ../../packages/shared
  brands:
    path: ../../packages/brands
  module_auth:
    path: ../../packages/modules/module_auth
  module_home:
    path: ../../packages/modules/module_home
  module_profile:
    path: ../../packages/modules/module_profile

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
PUBSPEC

cat > "$APP_DIR/lib/main.dart" <<MAIN
import 'package:brands/brands.dart';
import 'package:design_system/design_system.dart';
import 'package:flutter/material.dart';
import 'package:foundation/foundation.dart';
import 'package:get/get.dart';
import 'package:module_auth/module_auth.dart';
import 'package:module_home/module_home.dart';
import 'package:module_profile/module_profile.dart';
import 'package:shared/shared.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final config = BrandProfiles.${BRAND_PROFILE}(env: AppEnv.${APP_ENV});
  final moduleCatalog = <String, AppModule>{
    'module_auth': ModuleAuth(),
    'module_home': ModuleHome(),
    'module_profile': ModuleProfile(),
  };
  final modules = ModuleSelector.select(
    catalog: moduleCatalog,
    enabledModules: config.enabledModules,
  );

  final registry = await AppBootstrapper.bootstrap(config: config, modules: modules);

  runApp(
    _AppRoot(
      config: config,
      pages: registry.collectPages(),
    ),
  );
}

class _AppRoot extends StatelessWidget {
  const _AppRoot({required this.config, required this.pages});

  final AppConfig config;
  final List<GetPage<dynamic>> pages;

  @override
  Widget build(BuildContext context) {
    final debugPage = GetPage<dynamic>(
      name: AppRoutes.debugModules,
      page: () => ModuleDebugPage(
        config: config,
        registry: serviceLocator<ModuleRegistry>(),
        capabilityRegistry: serviceLocator<CapabilityRegistry>(),
      ),
    );

    return GetMaterialApp(
      title: config.appName,
      debugShowCheckedModeBanner: false,
      theme: AppThemeFactory.light(config.brandConfig),
      initialRoute: AppRoutes.authLogin,
      getPages: <GetPage<dynamic>>[
        ...pages,
        debugPage,
      ],
    );
  }
}
MAIN

echo "Created $APP_DIR with brand=$BRAND_PROFILE env=$APP_ENV"
echo "Next: (cd $APP_DIR && flutter pub get && flutter run)"
